#!/bin/bash

cd ~/bowtie2
mkdir ~/gene_coverage
mkdir ~/gene_coverage/arg_vf
mkdir ~/gene_coverage/arg_novf
mkdir ~/gene_coverage/mge_vf
mkdir ~/gene_coverage/mge_novf

#ARGs with VFs
for i in {1..36}
do
        seqkit subseq --gtf ~/ARG_MGE_manually_gtf/bin.${i}.nucl.uniq.ARGminer.dmnd.vf.gtf.txt ~/cdhit/bin.${i}.nucl.uniq -o ~/ARGs/bin.${i}.arg.vf.gtf.gene.fasta #the gtf file was prepared manually
        bowtie2-build ~/ARGs/bin.${i}.arg.vf.gtf.gene.fasta bin.${i}.arg.vf.bt2.index
        
        bowtie2 -x ~/bowtie2/bin.${i}.arg.vf.bt2.index -1 ~/clean_read/S1_1.fastq -2 ~/clean_read/S1_2.fastq -S bin.${i}.arg.vf.S1.sam -p 16
        pileup.sh in=bin.${i}.arg.vf.S1.sam out=~/gene_coverage/arg_vf/bin.${i}.arg.vf.S1.sam.map.txt
        rm bin.${i}.arg.vf.S1.sam
        
        bowtie2 -x ~/bowtie2/bin.${i}.arg.vf.bt2.index -1 ~/clean_read/S3_1.fastq -2 ~/clean_read/S3_2.fastq -S bin.${i}.arg.vf.S3.sam -p 16
        pileup.sh in=bin.${i}.arg.vf.S3.sam out=~/gene_coverage/arg_vf/bin.${i}.arg.vf.S3.sam.map.txt
        rm bin.${i}.arg.vf.S3.sam
        
        bowtie2 -x ~/bowtie2/bin.${i}.arg.vf.bt2.index -1 ~/clean_read/AT_1.fastq -2 ~/clean_read/AT_2.fastq -S bin.${i}.arg.vf.AT.sam -p 16
        pileup.sh in=bin.${i}.arg.vf.AT.sam out=~/gene_coverage/arg_vf/bin.${i}.arg.vf.AT.sam.map.txt
        rm bin.${i}.arg.vf.AT.sam
done

#ARGs without VFs
for i in {1..36}
do
        seqkit subseq --gtf ~/ARG_MGE_manually_gtf/bin.${i}.nucl.uniq.ARGminer.dmnd.novf.gtf.txt ~/cdhit/bin.${i}.nucl.uniq -o ~/ARGs/bin.${i}.arg.novf.gtf.gene.fasta #the gtf file was prepared manually
        bowtie2-build ~/ARGs/bin.${i}.arg.novf.gtf.gene.fasta bin.${i}.arg.novf.bt2.index
        
        bowtie2 -x ~/bowtie2/bin.${i}.arg.novf.bt2.index -1 ~/clean_read/S1_1.fastq -2 ~/clean_read/S1_2.fastq -S bin.${i}.arg.novf.S1.sam -p 16
        pileup.sh in=bin.${i}.arg.novf.S1.sam out=~/gene_coverage/arg_novf/bin.${i}.arg.novf.S1.sam.map.txt
        rm bin.${i}.arg.novf.S1.sam
        
        bowtie2 -x ~/bowtie2/bin.${i}.arg.novf.bt2.index -1 ~/clean_read/S3_1.fastq -2 ~/clean_read/S3_2.fastq -S bin.${i}.arg.novf.S3.sam -p 16
        pileup.sh in=bin.${i}.arg.novf.S3.sam out=~/gene_coverage/arg_novf/bin.${i}.arg.novf.S3.sam.map.txt
        rm bin.${i}.arg.novf.S3.sam
        
        bowtie2 -x ~/bowtie2/bin.${i}.arg.novf.bt2.index -1 ~/clean_read/AT_1.fastq -2 ~/clean_read/AT_2.fastq -S bin.${i}.arg.novf.AT.sam -p 16
        pileup.sh in=bin.${i}.arg.novf.AT.sam out=~/gene_coverage/arg_vf/bin.${i}.arg.novf.AT.sam.map.txt
        rm bin.${i}.arg.novf.AT.sam
done

#MGEs with VFs
for i in {1..36}
do
        seqkit subseq --gtf ~/ARG_MGE_manually_gtf/bin.${i}.nucl.uniq.MGE.dmnd.vf.gtf.txt ~/cdhit/bin.${i}.nucl.uniq -o ~/MGEs/bin.${i}.mge.vf.gtf.gene.fasta #the gtf file was prepared manually
        bowtie2-build ~/MGEss/bin.${i}.mge.vf.gtf.gene.fasta bin.${i}.mge.vf.bt2.index
        
        bowtie2 -x ~/bowtie2/bin.${i}.mge.vf.bt2.index -1 ~/clean_read/S1_1.fastq -2 ~/clean_read/S1_2.fastq -S bin.${i}.mge.vf.S1.sam -p 16
        pileup.sh in=bin.${i}.mge.vf.S1.sam out=~/gene_coverage/mge_vf/bin.${i}.mge.vf.S1.sam.map.txt
        rm bin.${i}.mge.vf.S1.sam
        
        bowtie2 -x ~/bowtie2/bin.${i}.mge.vf.bt2.index -1 ~/clean_read/S3_1.fastq -2 ~/clean_read/S3_2.fastq -S bin.${i}.mge.vf.S3.sam -p 16
        pileup.sh in=bin.${i}.mge.vf.S3.sam out=~/gene_coverage/mge_vf/bin.${i}.mge.vf.S3.sam.map.txt
        rm bin.${i}.mge.vf.S3.sam
        
        bowtie2 -x ~/bowtie2/bin.${i}.mge.vf.bt2.index -1 ~/clean_read/AT_1.fastq -2 ~/clean_read/AT_2.fastq -S bin.${i}.mge.vf.AT.sam -p 16
        pileup.sh in=bin.${i}.mge.vf.AT.sam out=~/gene_coverage/mge_vf/bin.${i}.mge.vf.AT.sam.map.txt
        rm bin.${i}.mge.vf.AT.sam
done

#ARGs without VFs
for i in {1..36}
do
        seqkit subseq --gtf ~/ARG_MGE_manually_gtf/bin.${i}.nucl.uniq.MGE.dmnd.novf.gtf.txt ~/cdhit/bin.${i}.nucl.uniq -o ~/MGEs/bin.${i}.mge.novf.gtf.gene.fasta #the gtf file was prepared manually
        bowtie2-build ~/MGEs/bin.${i}.mge.novf.gtf.gene.fasta bin.${i}.mge.novf.bt2.index
        
        bowtie2 -x ~/bowtie2/bin.${i}.mge.novf.bt2.index -1 ~/clean_read/S1_1.fastq -2 ~/clean_read/S1_2.fastq -S bin.${i}.mge.novf.S1.sam -p 16
        pileup.sh in=bin.${i}.mge.novf.S1.sam out=~/gene_coverage/mge_novf/bin.${i}.mge.novf.S1.sam.map.txt
        rm bin.${i}.mge.novf.S1.sam
        
        bowtie2 -x ~/bowtie2/bin.${i}.mge.novf.bt2.index -1 ~/clean_read/S3_1.fastq -2 ~/clean_read/S3_2.fastq -S bin.${i}.mge.novf.S3.sam -p 16
        pileup.sh in=bin.${i}.mge.novf.S3.sam out=~/gene_coverage/mge_novf/bin.${i}.mge.novf.S3.sam.map.txt
        rm bin.${i}.mge.novf.S3.sam
        
        bowtie2 -x ~/bowtie2/bin.${i}.mge.novf.bt2.index -1 ~/clean_read/AT_1.fastq -2 ~/clean_read/AT_2.fastq -S bin.${i}.mge.novf.AT.sam -p 16
        pileup.sh in=bin.${i}.mge.novf.AT.sam out=~/gene_coverage/mge_novf/bin.${i}.mge.novf.AT.sam.map.txt
        rm bin.${i}.mge.novf.AT.sam
done
